# Site settings
title: Roger's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.differentpla.net" # the base hostname & protocol for your site

# Conversion
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-redirect-from

strict_front_matter: true
